## Math test

In [32]:
import tensorflow as tf
import numpy as np

vocab_size = 4

In [33]:
ones_simetral = tf.ones(
    (4,4), dtype=tf.dtypes.float32, name=None
)

bias = np.random.rand(1,4)
print(bias)
tf_bias = tf.convert_to_tensor(bias, np.float32)

[[0.51651828 0.98492998 0.41675324 0.16747722]]


In [34]:
print(tf_bias * ones_simetral)
tf_bias_matrix = tf_bias * ones_simetral

tf.Tensor(
[[0.5165183  0.98493    0.41675323 0.16747722]
 [0.5165183  0.98493    0.41675323 0.16747722]
 [0.5165183  0.98493    0.41675323 0.16747722]
 [0.5165183  0.98493    0.41675323 0.16747722]], shape=(4, 4), dtype=float32)


In [35]:
bias_tilde = np.random.rand(4,1)
tf_bias_tilde =  tf.convert_to_tensor(bias_tilde, np.float32)
tf.convert_to_tensor(bias_tilde, np.float32)
tf_bias_tilde_matrix = tf_bias_tilde * ones_simetral

In [36]:
print(tf_bias_tilde_matrix)

tf.Tensor(
[[0.30603155 0.30603155 0.30603155 0.30603155]
 [0.1455464  0.1455464  0.1455464  0.1455464 ]
 [0.5700906  0.5700906  0.5700906  0.5700906 ]
 [0.5865859  0.5865859  0.5865859  0.5865859 ]], shape=(4, 4), dtype=float32)


In [37]:
tf_X = tf.convert_to_tensor(np.random.rand(4,4),dtype=np.float32)
print(tf_X)
log_X = tf.math.log(tf_X)
print(log_X)

tf.Tensor(
[[0.7885684  0.24079955 0.6829226  0.26586384]
 [0.55431426 0.48934752 0.1861488  0.17555568]
 [0.0985202  0.51888245 0.8480149  0.95098037]
 [0.339321   0.21398328 0.54924995 0.9360284 ]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[-0.23753616 -1.4237905  -0.38137376 -1.324771  ]
 [-0.5900235  -0.7146824  -1.6812088  -1.739799  ]
 [-2.3174937  -0.6560779  -0.16485709 -0.05026186]
 [-1.0808088  -1.5418574  -0.5992017  -0.06610944]], shape=(4, 4), dtype=float32)


In [38]:
dims_embedding = 2
weights = np.random.rand(4,dims_embedding)
tf_weights = tf.convert_to_tensor(weights, np.float32)

weights_tilde = np.random.rand(dims_embedding,4)
tf_weights_tilde = tf.convert_to_tensor(weights_tilde, np.float32)

print(tf_weights)
print(tf_weights_tilde)
product = tf.matmul(tf_weights,tf_weights_tilde)
print(product)

tf.Tensor(
[[0.9572906  0.32148942]
 [0.5651821  0.2890979 ]
 [0.54339063 0.18003087]
 [0.09952864 0.33400756]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[0.21928656 0.9226896  0.76965404 0.7426393 ]
 [0.05408794 0.7736892  0.3551617  0.20436336]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[0.22730966 1.132015   0.8509633  0.7766223 ]
 [0.13957354 0.74515957 0.53767115 0.47880745]
 [0.12889576 0.64066887 0.48216286 0.44033495]
 [0.03989107 0.3502521  0.19522932 0.14217278]], shape=(4, 4), dtype=float32)


In [39]:
summed_all = product + tf_bias_matrix + tf_bias_tilde_matrix
print(summed_all)
print(log_X)

tf.Tensor(
[[1.0498595  2.4229765  1.5737481  1.2501311 ]
 [0.80163825 1.875636   1.0999708  0.79183114]
 [1.2155046  2.1956894  1.4690068  1.1779027 ]
 [1.1429952  1.921768   1.1985685  0.8962359 ]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[-0.23753616 -1.4237905  -0.38137376 -1.324771  ]
 [-0.5900235  -0.7146824  -1.6812088  -1.739799  ]
 [-2.3174937  -0.6560779  -0.16485709 -0.05026186]
 [-1.0808088  -1.5418574  -0.5992017  -0.06610944]], shape=(4, 4), dtype=float32)


In [59]:
print(summed_all - log_X)
subtracted = summed_all - log_X

tf.Tensor(
[[1.2873957 3.846767  1.9551219 2.574902 ]
 [1.3916618 2.5903184 2.7811797 2.53163  ]
 [3.5329983 2.8517673 1.6338639 1.2281646]
 [2.223804  3.4636254 1.7977701 0.9623453]], shape=(4, 4), dtype=float32)


In [60]:
print(tf.math.reduce_sum(summed_all - log_X))

tf.Tensor(36.653313, shape=(), dtype=float32)


In [61]:
XMAX = 100
def cut_function(value):
    if value > XMAX:
        return 1
    else:
        return tf.math.pow(tf.divide(value,XMAX),alpha)
    
def cut_function2(value):
    clipped = tf.clip_by_value(value, clip_value_min = 0, clip_value_max=XMAX)
    print(clipped)
    return clipped / XMAX

In [67]:
X = tf.convert_to_tensor(np.random.rand(4,4)*130,dtype=np.float32)
print(X)
print(cut_function2(X))
    
end = tf.math.square(subtracted - cut_function2(X))
loss = tf.math.reduce_sum(end)
print(loss)

tf.Tensor(
[[120.83332    72.18738    76.18646   110.489845 ]
 [ 66.97272    85.3959    116.52585   123.14903  ]
 [ 21.214632   57.642494    1.9219834  51.093456 ]
 [  7.6039257 126.168015   55.36778    71.96442  ]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[100.         72.18738    76.18646   100.       ]
 [ 66.97272    85.3959    100.        100.       ]
 [ 21.214632   57.642494    1.9219834  51.093456 ]
 [  7.6039257 100.         55.36778    71.96442  ]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[1.         0.72187376 0.7618646  1.        ]
 [0.66972715 0.85395896 1.         1.        ]
 [0.21214633 0.57642496 0.01921983 0.5109346 ]
 [0.07603925 1.         0.5536778  0.7196442 ]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[100.         72.18738    76.18646   100.       ]
 [ 66.97272    85.3959    100.        100.       ]
 [ 21.214632   57.642494    1.9219834  51.093456 ]
 [  7.6039257 100.         55.36778    71.96442  ]], shape=(4, 4), dtype=float32)
tf.Tensor(54.422104, shape=(), d

In [69]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([8])
tf.pow(x, y)  # [[256, 65536], [9, 27]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 256,  256],
       [6561, 6561]])>

In [77]:
import numpy as np
tf.constant(0.0001) * tf.constant([[1.,1],[1.,1]])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.e-04, 1.e-04],
       [1.e-04, 1.e-04]], dtype=float32)>

In [ ]:
for i in range(0,1821):
    if(i % 10 == 0):
        print("10 zeilen geprüft")
    for j in range(0,1821):
        if(matrix[i,j] != matrix2[i,j]):
            print('Error')
        else:
            pass
        