## Math test

In [1]:
import tensorflow as tf
import numpy as np

vocab_size = 4

In [2]:
ones_simetral = tf.ones(
    (4,4), dtype=tf.dtypes.float32, name=None
)

bias = np.random.rand(1,4)
print(bias)
tf_bias = tf.convert_to_tensor(bias, np.float32)

[[0.16140465 0.17821371 0.03777957 0.94126967]]


In [3]:
print(tf_bias * ones_simetral)
tf_bias_matrix = tf_bias * ones_simetral

tf.Tensor(
[[0.16140465 0.17821372 0.03777957 0.9412697 ]
 [0.16140465 0.17821372 0.03777957 0.9412697 ]
 [0.16140465 0.17821372 0.03777957 0.9412697 ]
 [0.16140465 0.17821372 0.03777957 0.9412697 ]], shape=(4, 4), dtype=float32)


In [4]:
bias_tilde = np.random.rand(4,1)
tf_bias_tilde =  tf.convert_to_tensor(bias_tilde, np.float32)
tf.convert_to_tensor(bias_tilde, np.float32)
tf_bias_tilde_matrix = tf_bias_tilde * ones_simetral

In [5]:
print(tf_bias_tilde_matrix)

tf.Tensor(
[[0.95383364 0.95383364 0.95383364 0.95383364]
 [0.48047218 0.48047218 0.48047218 0.48047218]
 [0.42680278 0.42680278 0.42680278 0.42680278]
 [0.557357   0.557357   0.557357   0.557357  ]], shape=(4, 4), dtype=float32)


In [6]:
tf_X = tf.convert_to_tensor(np.random.rand(4,4),dtype=np.float32)
print(tf_X)
log_X = tf.math.log(tf_X)
print(log_X)

tf.Tensor(
[[0.554553   0.42607072 0.92048657 0.7832533 ]
 [0.96518916 0.99702406 0.02915673 0.8013419 ]
 [0.48126677 0.13028724 0.6014964  0.84369093]
 [0.3789324  0.05614571 0.39688057 0.70687234]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[-5.8959293e-01 -8.5314995e-01 -8.2852870e-02 -2.4429911e-01]
 [-3.5431176e-02 -2.9803775e-03 -3.5350697e+00 -2.2146760e-01]
 [-7.3133355e-01 -2.0380137e+00 -5.0833476e-01 -1.6996905e-01]
 [-9.7039747e-01 -2.8798048e+00 -9.2411989e-01 -3.4690520e-01]], shape=(4, 4), dtype=float32)


In [7]:
dims_embedding = 2
weights = np.random.rand(4,dims_embedding)
tf_weights = tf.convert_to_tensor(weights, np.float32)

weights_tilde = np.random.rand(dims_embedding,4)
tf_weights_tilde = tf.convert_to_tensor(weights_tilde, np.float32)

print(tf_weights)
print(tf_weights_tilde)
product = tf.matmul(tf_weights,tf_weights_tilde)
print(product)

tf.Tensor(
[[0.4114905  0.5435223 ]
 [0.25494236 0.1496242 ]
 [0.0902926  0.26695365]
 [0.7566002  0.41746986]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[0.8370749  0.95883226 0.7403817  0.5383628 ]
 [0.3789384  0.69558614 0.85130167 0.7580074 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[0.55040985 0.7726169  0.7673615  0.63352513]
 [0.2701042  0.3485235  0.31612998 0.25066775]
 [0.17674066 0.27226472 0.29410908 0.250963  ]
 [0.7915264  1.0158389  0.9155657  0.7237706 ]], shape=(4, 4), dtype=float32)


In [8]:
summed_all = product + tf_bias_matrix + tf_bias_tilde_matrix
print(summed_all)
print(log_X)

tf.Tensor(
[[1.6656482  1.9046643  1.7589748  2.5286283 ]
 [0.911981   1.0072094  0.8343817  1.6724097 ]
 [0.7649481  0.8772812  0.75869143 1.6190355 ]
 [1.510288   1.7514095  1.5107024  2.2223973 ]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[-5.8959293e-01 -8.5314995e-01 -8.2852870e-02 -2.4429911e-01]
 [-3.5431176e-02 -2.9803775e-03 -3.5350697e+00 -2.2146760e-01]
 [-7.3133355e-01 -2.0380137e+00 -5.0833476e-01 -1.6996905e-01]
 [-9.7039747e-01 -2.8798048e+00 -9.2411989e-01 -3.4690520e-01]], shape=(4, 4), dtype=float32)


In [9]:
print(summed_all - log_X)
subtracted = summed_all - log_X

tf.Tensor(
[[2.2552412  2.7578142  1.8418276  2.7729275 ]
 [0.94741213 1.0101898  4.3694515  1.8938773 ]
 [1.4962816  2.915295   1.2670262  1.7890046 ]
 [2.4806855  4.631214   2.4348223  2.5693026 ]], shape=(4, 4), dtype=float32)


In [10]:
print(tf.math.reduce_sum(summed_all - log_X))

tf.Tensor(37.432373, shape=(), dtype=float32)


In [11]:
XMAX = 100
def cut_function(value):
    if value > XMAX:
        return 1
    else:
        return tf.math.pow(tf.divide(value,XMAX),alpha)
    
def cut_function2(value):
    clipped = tf.clip_by_value(value, clip_value_min = 0, clip_value_max=XMAX)
    print(clipped)
    return clipped / XMAX

In [12]:
X = tf.convert_to_tensor(np.random.rand(4,4)*130,dtype=np.float32)
print(X)
print(cut_function2(X))
    
end = tf.math.square(subtracted - cut_function2(X))
loss = tf.math.reduce_sum(end)
print(loss)

tf.Tensor(
[[  3.5241644   8.691732   99.906395    1.3095466]
 [ 57.588013   78.62382    30.003      88.026276 ]
 [  4.058727  126.10544   111.31458   122.39462  ]
 [ 24.374079  116.6013    129.88637     3.3176575]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[  3.5241644   8.691732   99.906395    1.3095466]
 [ 57.588013   78.62382    30.003      88.026276 ]
 [  4.058727  100.        100.        100.       ]
 [ 24.374079  100.        100.          3.3176575]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[0.03524164 0.08691733 0.99906397 0.01309547]
 [0.5758801  0.7862382  0.30003    0.88026273]
 [0.04058727 1.         1.         1.        ]
 [0.24374078 1.         1.         0.03317657]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[  3.5241644   8.691732   99.906395    1.3095466]
 [ 57.588013   78.62382    30.003      88.026276 ]
 [  4.058727  100.        100.        100.       ]
 [ 24.374079  100.        100.          3.3176575]], shape=(4, 4), dtype=float32)
tf.Tensor(71.326324, shape=(), d

In [13]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([8])
tf.pow(x, y)  # [[256, 65536], [9, 27]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 256,  256],
       [6561, 6561]])>

In [14]:
import numpy as np
tf.constant(0.0001) * tf.constant([[1.,1],[1.,1]])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.e-04, 1.e-04],
       [1.e-04, 1.e-04]], dtype=float32)>

In [17]:
X[2:3,:]

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[  4.058727, 126.10544 , 111.31458 , 122.39462 ]], dtype=float32)>