In [8]:
import numpy as np
M = np.zeros((9,9))
for i in range(9):
    for j in range(9):
        M[i,j]=(i+1) * 10+ (j+1)
print(M)

[[11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [41. 42. 43. 44. 45. 46. 47. 48. 49.]
 [51. 52. 53. 54. 55. 56. 57. 58. 59.]
 [61. 62. 63. 64. 65. 66. 67. 68. 69.]
 [71. 72. 73. 74. 75. 76. 77. 78. 79.]
 [81. 82. 83. 84. 85. 86. 87. 88. 89.]
 [91. 92. 93. 94. 95. 96. 97. 98. 99.]]


In [9]:
def randfloat(min,max):
    return min + np.random.random() * (max-min)

blobs = 5
coMatrices = []
for blob_nr in range(blobs-1):
    N = np.zeros((9,9))
    for i in range(9):
        for j in range(9):
            new_entry = randfloat(0,M[i,j])
            N[i,j] = new_entry
            M[i,j] -= new_entry
    coMatrices.append(N)
#add the rest
coMatrices.append(M)


In [13]:
sum_ = np.zeros((9,9))
for matrix in coMatrices:
    sum_ = np.add(sum_,matrix)
print(sum_)

[[11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [41. 42. 43. 44. 45. 46. 47. 48. 49.]
 [51. 52. 53. 54. 55. 56. 57. 58. 59.]
 [61. 62. 63. 64. 65. 66. 67. 68. 69.]
 [71. 72. 73. 74. 75. 76. 77. 78. 79.]
 [81. 82. 83. 84. 85. 86. 87. 88. 89.]
 [91. 92. 93. 94. 95. 96. 97. 98. 99.]]
