In [1]:
import sys
sys.path.append("..")
import h5py
from Vocabulary import *
co_filepath = 'S:\\base_coocurrence_hdf'

In [2]:
unfiltered_vocab = Vocabulary()
unfiltered_vocab.load('..\\vocabs\\unfilteredbaseline')
print(unfiltered_vocab.get_size())

vocab = Vocabulary()
vocab.load('..\\vocabs\\baseline')
print(vocab.get_size())

5006400
148733


In [10]:
1 / 10

0.1

In [8]:
coocurrence[7,:]

array([4.000e+00, 9.700e+01, 8.904e+03, ..., 0.000e+00, 0.000e+00,
       0.000e+00], dtype=float32)

In [3]:
zeile = 0
spalte = 0
template = "co_occurence_{i}_{j}.hdf5".format(i=zeile,j=spalte)
file_path =  r'S:\base_coocurrence_hdf' + '\\' + template
        
tmp_hf = h5py.File(file_path, "r+")
coocurrence = tmp_hf.get("co-ocurrence")[:]
if (spalte > zeile):
    print('a')
    coocurrence = np.transpose(coocurrence)
#self.tf_co_occurences = tf.convert_to_tensor(coocurrence,dtype=tf.dtypes.float32)

print(coocurrence[0,0])
print(coocurrence[1,1])


vocab_first = vocab.id2Word[0]
vocab_second = vocab.id2Word[1]
print(vocab_first,vocab_second)

print(unfiltered_vocab.word_frequency[vocab_first])
print(unfiltered_vocab.word_frequency[vocab_second])

8.0
141.0
[[8.0000e+00 1.2000e+02 3.5700e+02 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.2000e+02 1.4100e+02 4.0660e+03 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [3.5700e+02 4.0660e+03 1.7509e+04 ... 2.4000e+01 1.5000e+01 6.0000e+00]
 ...
 [0.0000e+00 0.0000e+00 2.4000e+01 ... 2.1000e+01 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 1.5000e+01 ... 0.0000e+00 1.6000e+01 0.0000e+00]
 [0.0000e+00 0.0000e+00 6.0000e+00 ... 0.0000e+00 0.0000e+00 3.0000e+00]]
supersonic transport
2924
83190


In [6]:
path = '../coocurence data/'
import collections
import os
import sys
sys.path.append('..')
file_list = os.listdir(path)
from Vocabulary import *
from co_occurence import *
from scipy.sparse import dok_matrix,csr_matrix,lil_matrix
import scipy

vocab = Vocabulary()
vocab.load('../vocabs/baseline')
size = vocab.get_size()

capturer = Co_Occurence_Capturer()

block_size = 20000 # must be int
blocks_amount = math.ceil(vocab.get_size()/float(block_size))

#init
dict_of_dicts = {}
for i in range(blocks_amount):
    for j in range(blocks_amount):
        dict_of_dicts[(i,j)]={}

for file_name in file_list:
    #print(file_name)
    capturer.load_co_occurence(path + "/" + file_name)
    coOcc_local = capturer.co_occurences
    print(coOcc_local[0,0],coOcc_local[1,1])

145 1484
90 1752
51 1650
98 1169
12 557
68 1027
124 1432
198 1326
75 1183
66 1518
87 1601
76 1555
65 1471
60 1121
55 1278
61 1477
39 1690
58 1487
26 1209
31 1368
50 1436
37 1015
57 1204
20 1318
39 1322
43 1088
23 1244
24 1233
22 1313
52 1208
24 1200
32 1151
39 1140
28 1180
17 1180
44 1210
33 1065
34 1213
36 1114
31 1011
37 1095
18 1144
41 1182
39 1011
27 1218
22 1139
15 1126
23 1094
19 1001
28 881
29 1054
18 1199
28 997
25 1328
10 1190
32 1031
9 947
13 1250
22 1064
21 963
23 858
38 977
11 1136
28 1086
27 1025
19 836
12 1020
21 969
49 916
53 1050
11 475


In [7]:
path = r'..\\coocurrence_blocks\\'
filename = 'block_0_0'

with open(path+filename, 'rb+') as file:
        co_occurences = cloudpickle.load(file)
print(co_occurences[0,0],co_occurences[1,1])       
        

2938 83462
